name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: "Install Dependencies"
        run: bun install --frozen-lockfile
      - name: "Build"
        run: bun run build
      - name: "Setup Npm"
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - name: "Publish"
        run: |
          npm version --git-tag-version false ${{ github.event.release.tag_name }}
          npm publish --provenance --access public
