name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Bun"
        uses: oven-sh/setup-bun@0f37bd81694f91f7edc1c990461a7fc67ef7e3d8
        with:
          bun-version: 1.0.x
          scope: "@smart-discord"
      - name: "Install Dependencies"
        run: bun install --frozen-lockfile
      - name: "Build"
        run: bun run build
      - name: "Publish"
        run: npm publish
